import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Eye, EyeOff, LockKeyhole, Mail, UserRound, CheckSquare, ArrowRight } from 'lucide-react';
import { motion } from 'framer-motion';
import axiosInstance from '../api/axiosInstance';
import './auth.css';

export default function Register() {
  const navigate = useNavigate(); const [formData, setFormData] = useState({ fullName: '', email: '', password: '', confirmPassword: '' }); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [loading, setLoading] = useState(false); const [showPassword, setShowPassword] = useState(false); const [showConfirm, setShowConfirm] = useState(false);
  const handleChange = (e) => setFormData((p) => ({ ...p, [e.target.name]: e.target.value }));
  const handleSubmit = async (e) => { e.preventDefault(); setError(''); setSuccess(''); if (!formData.fullName || !formData.email || !formData.password || !formData.confirmPassword) return setError('All fields are required.'); if (formData.password !== formData.confirmPassword) return setError('Passwords do not match.'); try { setLoading(true); await axiosInstance.post('/Auth/register', { fullName: formData.fullName, email: formData.email, password: formData.password }); setSuccess('Registration successful. Redirecting to login…'); setTimeout(() => navigate('/login'), 900); } catch (err) { setError(err.response?.data?.message || err.response?.data?.error || 'Registration failed. Please try again.'); setLoading(false); } };
  return <div className="auth-page"><motion.div className="auth-shell" initial={{ opacity: 0, scale: .98, y: 12 }} animate={{ opacity: 1, scale: 1, y: 0 }} transition={{ duration: .35 }}><div className="auth-brand"><span className="brand-mark large"><CheckSquare size={24} /></span><div><strong>TaskFlow</strong><span>Organize. Prioritize. Deliver.</span></div></div><div className="auth-card"><div className="auth-heading"><span className="eyebrow">GET STARTED</span><h1>Create your account</h1><p>Join your workspace and start managing tasks smarter.</p></div><form onSubmit={handleSubmit}><div className="form-group"><label htmlFor="fullName">Full name</label><div className="input-wrap"><UserRound size={18} /><input id="fullName" name="fullName" type="text" value={formData.fullName} onChange={handleChange} placeholder="Your full name" autoComplete="name" required /></div></div><div className="form-group"><label htmlFor="email">Email address</label><div className="input-wrap"><Mail size={18} /><input id="email" name="email" type="email" value={formData.email} onChange={handleChange} placeholder="you@example.com" autoComplete="email" required /></div></div><div className="form-group"><label htmlFor="password">Password</label><div className="input-wrap"><LockKeyhole size={18} /><input id="password" name="password" type={showPassword ? 'text' : 'password'} value={formData.password} onChange={handleChange} placeholder="Create a password" autoComplete="new-password" required /><button className="input-action" type="button" onClick={() => setShowPassword((v) => !v)}>{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></div><div className="form-group"><label htmlFor="confirmPassword">Confirm password</label><div className="input-wrap"><LockKeyhole size={18} /><input id="confirmPassword" name="confirmPassword" type={showConfirm ? 'text' : 'password'} value={formData.confirmPassword} onChange={handleChange} placeholder="Repeat your password" autoComplete="new-password" required /><button className="input-action" type="button" onClick={() => setShowConfirm((v) => !v)}>{showConfirm ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></div>{error && <div className="alert error">{error}</div>}{success && <div className="alert success">{success}</div>}<button className="auth-submit" type="submit" disabled={loading || !!success}>{loading ? 'Creating account…' : <>Create account <ArrowRight size={18} /></>}</button></form><p className="auth-link">Already have an account? <Link to="/login">Sign in</Link></p></div></motion.div></div>;
}
