import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowLeft, CalendarDays, CheckCircle2, ClipboardList } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import axiosInstance from '../api/axiosInstance';
import Navbar from '../components/Navbar';
import { useAuth } from '../context/useAuth';

const initialFormData = { title: '', description: '', status: 0, priority: 1, category: '', dueDate: '', assignedToUserId: '' };

export default function TaskForm() {
  const navigate = useNavigate(); const { id } = useParams(); const { user } = useAuth();
  const isEditMode = Boolean(id); const isAdmin = String(user?.role || '').toLowerCase() === 'admin';
  const [formData, setFormData] = useState(initialFormData); const [error, setError] = useState(''); const [loading, setLoading] = useState(isEditMode); const [loadFailed, setLoadFailed] = useState(false);
  useEffect(() => { if (!isEditMode) return; let active = true; const controller = new AbortController(); const loadTask = async () => { try { const res = await axiosInstance.get(`/Tasks/${id}`, { signal: controller.signal }); if (!active) return; const task = res.data; if (!task || typeof task !== 'object' || Array.isArray(task)) throw new Error('Invalid task response.'); setFormData({ title: task.title || '', description: task.description || '', status: task.status === 'InProgress' || task.status === 1 ? 1 : task.status === 'Completed' || task.status === 2 ? 2 : 0, priority: task.priority === 'Low' || task.priority === 0 ? 0 : task.priority === 'High' || task.priority === 2 ? 2 : 1, category: task.category || '', dueDate: task.dueDate ? task.dueDate.split('T')[0] : '', assignedToUserId: task.assignedToUserId || '' }); setError(''); setLoadFailed(false); } catch (err) { if (!active || err?.name === 'CanceledError' || err?.code === 'ERR_CANCELED') return; setLoadFailed(true); setError(err?.response?.data?.message || err?.message || 'Failed to load task.'); } finally { if (active) setLoading(false); } }; loadTask(); return () => { active = false; controller.abort(); }; }, [id, isEditMode]);
  const handleChange = (e) => setFormData((prev) => ({ ...prev, [e.target.name]: e.target.value }));
  const handleSubmit = async (e) => { e.preventDefault(); setError(''); if (!formData.title.trim()) return setError('Title is required.'); if (isAdmin && !formData.assignedToUserId) return setError('Assigned To User ID is required.'); setLoading(true); const payload = { title: formData.title.trim(), description: formData.description || null, status: Number(formData.status), priority: Number(formData.priority), category: formData.category || null, dueDate: formData.dueDate || null, assignedToUserId: isAdmin ? Number(formData.assignedToUserId) : Number(user?.id || user?.userId || 0) }; try { if (isEditMode) await axiosInstance.put(`/Tasks/${id}`, payload); else await axiosInstance.post('/Tasks', payload); navigate(isEditMode ? `/tasks/${id}` : '/tasks'); } catch (err) { setError(err?.response?.data?.message || (isEditMode ? 'Failed to update task.' : 'Failed to create task.')); } finally { setLoading(false); } };
  if (loading && isEditMode && !formData.title) return <div className="page"><Navbar /><div className="empty-state"><h2>Loading task…</h2><p>Please wait while we load the task.</p></div></div>;
  if (isEditMode && loadFailed) return <div className="page"><Navbar /><div className="empty-state"><h2>Could not load task</h2><p className="auth-error">{error}</p><button type="button" onClick={() => navigate('/tasks')}>Back to Tasks</button></div></div>;
  return <div className="page"><Navbar /><motion.main className="task-form" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}><button className="back-button" type="button" onClick={() => navigate(isEditMode ? `/tasks/${id}` : '/tasks')}><ArrowLeft size={16} /> Back</button><div className="form-title"><span className="form-title-icon"><ClipboardList size={21} /></span><div><span className="eyebrow">TASK WORKSPACE</span><h1>{isEditMode ? 'Edit task' : 'Create a new task'}</h1><p>{isEditMode ? 'Update the details and keep the work moving.' : 'Capture the work, set a priority, and give it a clear deadline.'}</p></div></div>{error && <div className="alert error">{error}</div>}<form onSubmit={handleSubmit}><div className="form-group full"><label htmlFor="title">Task title</label><input id="title" name="title" type="text" value={formData.title} onChange={handleChange} placeholder="e.g. Prepare project presentation" disabled={loading} maxLength={200} /></div><div className="form-group full"><label htmlFor="description">Description</label><textarea id="description" name="description" value={formData.description} onChange={handleChange} placeholder="Add useful context, requirements, or notes…" disabled={loading} maxLength={2000} /></div><div className="form-group"><label htmlFor="status">Status</label><select id="status" name="status" value={formData.status} onChange={handleChange} disabled={loading}><option value="0">Pending</option><option value="1">In Progress</option><option value="2">Completed</option></select></div><div className="form-group"><label htmlFor="priority">Priority</label><select id="priority" name="priority" value={formData.priority} onChange={handleChange} disabled={loading}><option value="0">Low</option><option value="1">Medium</option><option value="2">High</option></select></div><div className="form-group"><label htmlFor="category">Category</label><input id="category" name="category" type="text" value={formData.category} onChange={handleChange} placeholder="e.g. Work, Study, Personal" disabled={loading} maxLength={100} /></div><div className="form-group"><label htmlFor="dueDate"><CalendarDays size={13} /> Due date</label><input id="dueDate" name="dueDate" type="date" value={formData.dueDate} onChange={handleChange} disabled={loading} /></div>{isAdmin && <div className="form-group full"><label htmlFor="assignedToUserId">Assigned To User ID</label><input id="assignedToUserId" name="assignedToUserId" type="number" min="1" value={formData.assignedToUserId} onChange={handleChange} placeholder="Enter user ID" disabled={loading} /></div>}<div className="form-actions"><button type="submit" disabled={loading}><CheckCircle2 size={16} />{loading ? (isEditMode ? 'Updating…' : 'Creating…') : (isEditMode ? 'Save changes' : 'Create task')}</button><button type="button" onClick={() => navigate(isEditMode ? `/tasks/${id}` : '/tasks')} disabled={loading}>Cancel</button></div></form></motion.main></div>;
}
